oneshirt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('trade.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trade/urls.py
from django.urls import path

from . import startup
from .views import index, auth, search, item, trade, admin, api

app_name = 'trade'
urlpatterns = [
    # Index
    path(r'', index.index, name='index'),
    path(r'about/', index.about, name='index_about'),
    path(r'mine/', index.mine, name='items_mine'),

    # Auth
    path(r'login/', auth.login, name='login'),
    path(r'logout/', auth.logout, name='logout'),
    path(r'register/', auth.register, name='register'),
    path(r'login/forgot/', auth.forgot, name='auth_forgot'),
    path(r'login/reset/', auth.reset, name='auth_reset'),

    # Items
    path(r'item/<int:id>/', item.view, name='item_view'),
    path(r'item/add/', item.new, name='item_add'),
    path(r'item/<int:id>/relist/', item.relist, name='item_relist'),

    # Trading
    path(r'trade/make', trade.new_trade, name='trade_new'),
    path(r'trade/accept', trade.accept, name='trade_accept'),
    path(r'trade/decline', trade.decline, name='trade_decline'),

    # Search
    path(r'search/', search.search, name='search'),
    path(r'search/do', search.do_search, name='search_do'),

    # Admin
    path(r'admin/', admin.home, name='admin_home'),
    path(r'admin/verify/<int:id>/', admin.verify, name='admin_verify'),
    path(r'admin/delete/<int:id>/', admin.delete, name='admin_delete'),
    path(r'feedback/', admin.feedback, name='admin_feedback'),
    path(r'test/', admin.test),

    # API
    path(r'api/all', api.all_items, name='api_all'),
    path(r'api/search', api.search, name='api_search'),
]

trade/models.py
import binascii
import os
from random import randint

from django.contrib.auth.models import User
from django.db import models


class FRCTeam(models.Model):
    key = models.CharField(max_length=10, primary_key=True)
    number = models.IntegerField()
    nickname = models.TextField()

    def __str__(self):
        return str(self.number)


class FRCComp(models.Model):
    compCode = models.CharField(max_length=30)
    shortName = models.TextField()
    longName = models.TextField()
    teams = models.ManyToManyField(FRCTeam)

    def __str__(self):
        return self.longName


class OneshirtUser(models.Model):
    django_user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    fname = models.CharField(max_length=60)
    email = models.CharField(max_length=100)
    team = models.ForeignKey(FRCTeam, on_delete=models.SET_NULL, null=True, blank=True, unique=False)

    def __str__(self):
        if self.team:
            return "%s from %s" % (self.fname, self.team)
        else:
            return "%s (no team)" % self.fname


class PasswordResetRequest(models.Model):
    def gen_key():
        k = binascii.b2a_hex(os.urandom(15))
        while len(PasswordResetRequest.objects.filter(key=k)) != 0:
            k = binascii.b2a_hex(os.urandom(15))
        return k

    user = models.ForeignKey(OneshirtUser, on_delete=models.CASCADE)
    key = models.CharField(primary_key=True, max_length=30, default=gen_key)
    valid = models.BooleanField(default=True)

    def __str__(self):
        if self.valid:
            return "Valid reset for %s" % self.user
        else:
            return "Invalid reset for %s" % self.user


class Item(models.Model):
    item_types = (
        ('ts', "T-Shirt"),
        ('hat', "Hat"),
        ('zip', "Zip-Up Hoodie"),
        ('pull', "Pullover Hoodie"),
        ('swt', "Sweater"),
        ('pnt', "Pants"),
        ('sk', "Socks"),
        ('etc', "Doodad/Other"),
    )

    def generate_id():  # Generate an ID for an item
        id = randint(100, 1000000)
        while len(Item.objects.filter(id=id)) != 0:
            id = randint(100, 1000000)
        return id

    id = models.PositiveIntegerField(primary_key=True, default=generate_id, editable=False)
    owner = models.ForeignKey(OneshirtUser, on_delete=models.CASCADE)
    team = models.IntegerField()
    year = models.IntegerField(null=True, blank=True)
    classification = models.CharField(max_length=10, choices=item_types)
    description = models.TextField()
    available = models.BooleanField(default=True)
    photo = models.ImageField(null=True)
    verified = models.BooleanField(default=False)

    def __str__(self):
        if self.team > 0:
            if self.year and self.year > 0:
                return "%s %s (%s)" % (self.team, self.get_classification_display(), self.year)
            else:
                return "%s %s" % (self.team, self.get_classification_display())
        else:
            if self.year and self.year > 0:
                return "%s (%s, no team)" % (self.get_classification_display(), self.year)
            else:
                return "%s (no team)" % self.get_classification_display()


class Trade(models.Model):
    statuses = (
        ('a', 'Accepted'),
        ('d', 'Denied'),
        ('p', 'Pending'),
        ('c', 'Cancelled'),
    )
    requester = models.ForeignKey(OneshirtUser, null=False, blank=False, on_delete=models.CASCADE,
                                  related_name="trade_user_requester")
    recipient = models.ForeignKey(OneshirtUser, null=False, blank=False, on_delete=models.CASCADE,
                                  related_name="trade_user_recipient")
    give = models.ForeignKey(Item, null=False, blank=False, on_delete=models.CASCADE, related_name="trade_item_given")
    take = models.ForeignKey(Item, null=False, blank=False, on_delete=models.CASCADE, related_name="trade_item_gotten")
    status = models.CharField(max_length=10, choices=statuses, default='p')

    def __str__(self):
        return "%s offering %s for %s from %s" % (
            self.requester, str(self.give), str(self.take), self.recipient
        )

trade/views/admin.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

from .. import email
from ..models import Trade, Item, OneshirtUser


def home(request):
    if not request.user.is_staff:
        return HttpResponse(status=400)

    ctx = {}
    cards = []

    for item in Item.objects.filter(verified=False).order_by('?')[:20]:
        cards.append(render_to_string("trade/partial/item_card.html", {"item": item}))

    ctx['cards'] = cards

    return render(request, 'trade/index_home.html', ctx)


def verify(request, id):
    if request.user.is_staff:
        i = get_object_or_404(Item, id=id)
        i.verified = True
        i.save()

    return redirect('trade:admin_home')


def delete(request, id):  # This function is accessable to users. TODO: Refactor into item.py
    i = get_object_or_404(Item, id=id)

    if request.user.is_staff or request.user == i.owner.django_user:
        i.delete()

    return redirect('trade:admin_home')


def feedback(request):
    if not request.method == 'POST':
        return HttpResponse(status=400)

    try:
        u = get_object_or_404(OneshirtUser, django_user=request.user)
        email.feedback_mail(request.POST.get('feedback'), u)
    except Exception as e:
        print(e)
        # return render(request, 'trade/message.html', {'message': e})

    return redirect('trade:index')


def test(request):
    ctx = {'trade': Trade.objects.get(id=2)}
    return render(request, 'trade/email/trade_accepted.html', ctx)

trade/views/api.py
from django.http import JsonResponse
from django.db.models import Q

from ..models import Item


def all_items(request):
    resp = []

    for item in Item.objects.filter(verified=True):
        resp.append({
            'name': str(item),
            'team': item.team,
            'description': item.description,
            'type': item.get_classification_display(),
            'id': item.id,
            'photo': item.photo.url,
        })

    return JsonResponse({'items': resp})


def search(request):
    resp = []
    data = request.GET

    q = Q(verified=True)
    if 'team' in request.GET:
        q &= Q(team=int(data['team']))
    if 'year' in request.GET:
        q &= Q(year=int(data['year']))

    for item in Item.objects.filter(q):
        resp.append({
            'name': str(item),
            'team': item.team,
            'description': item.description,
            'type': item.get_classification_display(),
            'id': item.id,
            'photo': item.photo.url,
        })

    return JsonResponse(resp)

trade/views/index.py
from django.shortcuts import render
from django.template.loader import render_to_string

from ..models import Item


def index(request):
    ctx = {}
    cards = []

    for item in Item.objects.filter(available=True).filter(verified=True).order_by('?')[:20]:
        cards.append(render_to_string("trade/partial/item_card.html", {"item": item}))

    ctx['cards'] = cards
    ctx['page'] = "index"

    return render(request, 'trade/index_home.html', ctx)


def about(request):
    return render(request, 'trade/index_about.html')


def mine(request):
    ctx = {}
    cards = []

    for item in Item.objects.filter(owner__django_user=request.user):
        cards.append(render_to_string("trade/partial/item_card.html", {"item": item}))

    ctx['cards'] = cards
    ctx['page'] = mine

    return render(request, 'trade/index_home.html', ctx)

trade/views/item.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .. import email, utils
from ..models import Item, OneshirtUser, Trade, FRCComp


def view(request, id):
    ctx = {}
    i = get_object_or_404(Item, id=id)

    if request.user.is_authenticated:
        ctx['items'] = Item.objects.filter(owner__django_user=request.user)

    if request.user.is_authenticated and request.user == i.owner.django_user:
        requests = Trade.objects.filter(take__id=i.id).exclude(status="d")
        ctx['requests'] = requests

    if request.user.is_authenticated and request.user != i.owner.django_user:
        ctx['trade_active'] = Trade.objects.filter(take__id=i.id, requester__django_user=request.user)

    if i.owner.team:
        ctx['events'] = utils.list_with_and(list(FRCComp.objects.filter(teams=i.owner.team)))

    ctx['item'] = i

    return render(request, 'trade/item_view.html', ctx)


def new(request):
    if request.method == 'GET':
        ctx = {}
        ctx['types'] = Item.item_types

        return render(request, 'trade/item_add.html', ctx)
    else:
        data = request.POST
        if not ('photo' in request.FILES and 'team' in data and 'type' in data):
            # assert False
            return HttpResponse(status=400)

        if request.FILES['photo'].size > 5500000:
            ctx = {}
            ctx['title'] = "File too large"
            ctx['message'] = "Please make sure that the photo you upload is less than 5mb in size."
            return render(request, 'trade/message.html')

        osu = get_object_or_404(OneshirtUser, django_user=request.user)
        i = Item()
        i.owner = osu
        i.team = data['team']
        if data.get('year'):
            i.year = data.get('year')
        i.classification = data['type']
        i.description = data.get('description')
        i.photo = request.FILES['photo']
        i.save()

        return redirect('trade:item_view', id=i.id)


def relist(request, id):
    i = get_object_or_404(Item, id=id)

    if not (i.owner.django_user == request.user or request.user.is_staff):
        return HttpResponse(status=401)

    i.available = True
    i.save()

    for t in Trade.objects.filter(take=i, status='a'):
        t.status = 'c'
        t.save()

        try:
            email.trade_cancelled_by_taker(t)
        except Exception as e:
            print(e)

    for t in Trade.objects.filter(give=i, status='a'):
        t.status = 'c'
        t.save()

        try:
            email.trade_cancelled_by_giver(t)
        except Exception as e:
            print(e)

    return redirect('trade:item_view', id=id)

trade/views/search.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http.response import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from ..models import Item, OneshirtUser


def search(request):
    ctx = {}
    ctx['item_types'] = Item.item_types

    try:
        ctx['team'] = OneshirtUser.objects.get(django_user=request.user).team
    except (ObjectDoesNotExist, TypeError):
        pass

    return render(request, 'trade/search.html', ctx)


def do_search(request):
    if request.method == "GET":
        q = Q(verified=True)

        if request.GET.get('team'):
            q = q & Q(team=request.GET['team'])
        if request.GET.get('type') != 'any':
            q = q & Q(classification=request.GET['type'])

        if request.GET.get('my_events') == 'true' and request.user.is_authenticated:
            osu = OneshirtUser.objects.filter(django_user=request.user).first()

            if osu.team:
                events = osu.team.frccomp_set.all()

                eq = Q()

                for event in events:
                    for team in event.teams.all():
                        eq = eq | Q(owner__team__number=team.number)

                q = q & eq

        q & Q(available=True)

        items = Item.objects.filter(q)

        out = {"items": []}
        for item in items:
            ctx = {"item": item}
            out['items'].append(render_to_string("trade/partial/item_card.html", ctx, request))

        return JsonResponse(out)

trade/views/trade.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt

from ..email import trade_mail, trade_accepted_mail
from ..models import Item, Trade, OneshirtUser


def new_trade(request):
    if request.method == 'POST':
        data = request.POST

        t = Trade()
        t.requester = get_object_or_404(OneshirtUser, django_user=request.user)
        t.recipient = get_object_or_404(OneshirtUser, django_user__username=data['item_owner'])
        t.give = (get_object_or_404(Item, id=data['give']))
        t.take = (get_object_or_404(Item, id=data['take']))
        t.save()

        try:
            trade_mail(t)
        except Exception as e:
            print(e)

        return redirect('trade:item_view', id=data['take'])


@csrf_exempt
def accept(request):
    if request.method == 'POST':
        t = get_object_or_404(Trade, id=request.POST['id'])
        t.status = 'a'
        t.give.available = False
        t.take.available = False

        t.give.save()
        t.take.save()
        t.save()

        try:
            trade_accepted_mail(t)
        except Exception as e:
            print(e)

        return JsonResponse({"success": True})

    return JsonResponse({}, status=400)

@csrf_exempt
def decline(request):
    if request.method == 'POST':
        t = get_object_or_404(Trade, id=request.POST['id'])
        t.status = 'd'
        t.save()

        return JsonResponse({"success": True})

    return JsonResponse({}, status=400)

trade/templates/trade/auth_forgot_pass.html
{% extends 'trade/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 col-md-4 ml-auto mr-auto">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Forgot Password</h4>
          <form action="{% url 'trade:auth_forgot' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="email">Email</label>
              <input required type="email" class="form-control" name="email" id="email"
                     placeholder="dominic@frcshirt.trade">
            </div>
            <button class="btn btn-primary" type="submit">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

trade/templates/trade/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}

  <title>{% block title %}FRCShirt{% endblock %}</title>

  <link rel="shortcut icon" href="{% static 'trade/mono_badge_128.png' %}">
  <link rel="icon" href="{% static 'trade/mono_badge_256.png' %}">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

  <!-- Import Bootstrap -->
  <link rel="stylesheet" href="{% static 'trade/bootstrap.css' %}">

  <!-- Required Bootstrap meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- End required Bootstrap meta tags -->

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>

  <meta name="theme-color" content="#2b2b2b">

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68938103-6"></script>
  <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
          dataLayer.push(arguments);
      }

      gtag('js', new Date());

      gtag('config', 'UA-68938103-6');
  </script>

  {% block script %}{% endblock %}
  {% block style %}{% endblock %}
</head>
<body>
<!-- Nav Bar -->
<nav class="navbar navbar-expand-md navbar-dark bg-secondary fixed-top">
  <a class="navbar-brand" href="{% url 'trade:index' %}">
    <img src="{% static 'trade/shirt_gradient.svg' %}" height=40>
  </a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navItems"
          aria-controls="navItems" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navItems">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trade:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trade:index_about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trade:search' %}">Search</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#" data-target="#login_modal" data-toggle="modal">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'trade:register' %}">Register</a>
        </li>
      {% else %}
        {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trade:admin_home' %}">Admin Home</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'trade:items_mine' %}">My Items</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'trade:logout' %}">Log Out</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
<!-- Login modal -->
<div class="modal fade" id="login_modal" tabindex="-1" role="document" aria-hidden="true" aria-labelledby="login_label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="login_label">Log In</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'trade:login' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label for="username">Username</label>
            <input required type="text" class="form-control" name="username" id="username" placeholder="Username">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input required type="password" class="form-control" name="password" id="password" placeholder="Password">
          </div>
          <p class="modal-text"><a href="{% url 'trade:auth_forgot' %}">Forgot Password</a></p>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Log In</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>


<div class="modal fade" id="feedback_modal" tabindex="-1" role="document" aria-hidden="true"
     aria-labelledby="feedback_label">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="feedback_label">Send Feedback</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'trade:admin_feedback' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <textarea class="form-control" name="feedback" id="feedback" placeholder="Feedback"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Send</button>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% block modals %}
{% endblock %}

<main class="container-fluid" style="padding-top: 70px;">
  {% block content %}
    Hello World! Override me!
  {% endblock %}
  <hr style="margin-top: 15px;">
  <div class="footer container-fluid text-center" style="margin-bottom: 15px;">
    <small>&copy;Dominic Canora<br>
      Made with &hearts;, available on <a href="https://github.com/dc74089/oneshirt">GitHub</a>.
    </small>
    <br>
    {% if request.user.is_authenticated %}
      <small><a href="#" data-target="#feedback_modal" data-toggle="modal">Send Feedback</a></small>
    {% endif %}
  </div>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>
</body>
</html>

trade/templates/trade/item_view.html
{% extends 'trade/base.html' %}
{% load thumbnail %}

{% block script %}
  <script>
      function acceptTrade(id) {
          $.post("{% url 'trade:trade_accept' %}", {"id": id}, function (data) {
              location.reload(true);
          });
      }

      function declineTrade(id) {
          $.post("{% url 'trade:trade_decline' %}", {"id": id}, function (data) {
              location.reload(true);
          });
      }
  </script>
{% endblock %}

{% block modals %}
  {% for req in requests %}
    <div class="modal" tabindex="-1" role="dialog" id="reqmod-{{ req.id }}" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">View Trade</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% thumbnail req.give.photo "1000" as thumb %}
              <img style="width: 100%; clear:both;" src="{{ thumb.url }}">
            {% endthumbnail %}
            <br><br>
            <h4 class="text-center">{{ req.give }}</h4>
            <p class="text-center">{{ req.give.description }}<br>Offered by {{ req.give.owner }}</p>
          </div>
          {% if req.status == "p" %}
            <div class="modal-footer">
              <small>If you accept, {{ req.give.owner.fname }} will receive your email address so they can coordinate
                the trade. If you decline, it is <b>irreversible</b> and you will not be able to later accept.
              </small>
              <button type="button" class="btn btn-primary" onclick="acceptTrade({{ req.id }});">Accept</button>
              <button type="button" class="btn btn-danger" onclick="declineTrade({{ req.id }});">Decline</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          {% elif req.status == "d" %}
            <div class="modal-footer">
              <p class="modal-text">You've declined this offer. </p>
            </div>
          {% else %}
            <div class="modal-footer">
              <p class="modal-text">You've already accepted this trade! {{ req.give.owner.fname }} will be emailing you
                soon. </p>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-sm-6 col-md-4">
      <div class="card">
        <div class="card-body">
          {% thumbnail item.photo "1000" upscale=False as thumb %}
            <img style="width: 100%; clear:both;" src="{{ thumb.url }}">
          {% endthumbnail %}
          <br><br>
          <h4 class="text-center">{{ item }}</h4>
          <p class="text-center">{{ item.description }}<br>Listed by {{ item.owner }}</p>
          {% if events %}
            <p style="font-size: 0.8em;" class="text-center">{{ item.owner.fname }}'s team will be at {{ events }} this
              season.</p>
          {% endif %}
        </div>
          <div class="card-footer">
            {% if request.user.is_staff and not item.verified %}
              <a class="btn btn-primary" href="{% url 'trade:admin_verify' id=item.id %}">Verify</a>
            {% endif %}
            {% if request.user.is_staff or request.user == item.owner.django_user %}
              <a class="btn btn-danger" href="{% url 'trade:admin_delete' id=item.id %}">Delete</a>
            {% endif %}
          </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-4">
      {% if request.user != item.owner.django_user %}
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">I Want It!</h4>
            {% if user.is_authenticated %}
              {% if not trade_active %}
                <h6>Set up a trade with {{ item.owner }}.</h6>
                <br>
                {% if items %}
                  <form action="{% url 'trade:trade_new' %}" method="post">
                    {% csrf_token %}
                    <input type="number" readonly name="take" class="d-none" value="{{ item.id }}">
                    <input type="text" readonly name="item_owner" class="d-none"
                           value="{{ item.owner.django_user.username }}">

                    <div class="form-group">
                      <label for="give">What do you want to offer?</label>
                      <select class="custom-select" name="give" style="width: 100%;">
                        {% for item in items %}
                          <option value="{{ item.id }}">My {{ item }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <button class="btn btn-primary" type="submit">Submit</button>
                  </form>
                {% else %}
                  <p class="card-text">You need to add an item before you can make an offer!</p>
                {% endif %}
              {% else %}
                <p>You already have a trade active! You will get an email from the item owner when they
                  approve or deny
                  your request.</p>
              {% endif %}
            {% else %}
              <p>To set up a trade, you need to be logged in! Log in or register using one of the buttons
                in the header,
                then come back here.</p>
            {% endif %}
          </div>
        </div>
      {% else %}
        <div class="card">
          <div class="card-body">
            {% if requests %}
              <h5 class="card-title">People Want This!</h5>
              <div class="list-group list-group-flush">
                {% for req in requests %}
                  <a class="list-group-item list-group-item-action" data-toggle="modal"
                     data-target="#reqmod-{{ req.id }}" style="padding-left: 0px;">
                    {{ req.requester }} wants to trade {{ req.give }}</a>
                {% endfor %}
              </div>
            {% else %}
              <h5 class="card-title">No offers yet!</h5>
              <p class="card-text">Nobody has tried to trade for this item yet. You can offer it in a
                trade, though!</p>
            {% endif %}
          </div>
        </div>
        {% if not item.available %}
          <div class="card" style="margin-top: 10px;">
            <div class="card-body">
              <h5 class="card-title">Off the Market</h5>
              <p class="card-text">Since you've accepted a trade, this item has been <b>taken off the market</b> and <b>won't
                show up on the homepage or in search results</b>. If the trade that you accepted has fallen through, you
                can <a href="{% url 'trade:item_relist' id=item.id %}">mark this item as available</a> so that others
                can see this item again and request to
                trade for it. Note that when you re-list an item, any of the people that you have an active trade with
                <b>will be emailed that your trade has been cancelled</b>.</p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
  </div>
{% endblock %}

trade/templates/trade/message.html
{% extends "trade/base.html" %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 col-md-4 ml-auto mr-auto">
      <div class="card">
        <div class="card-body">
          {% if title %}
            <h4 class="card-title">{{ title }}</h4>
          {% endif %}

          <p class="card-text">{{ message | safe }}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}